# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 372)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 10, 151, 61))
        self.label.setObjectName("label")
        self.label_radius_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_radius_2.setGeometry(QtCore.QRect(130, 100, 111, 21))
        self.label_radius_2.setObjectName("label_radius_2")
        self.label_lenght = QtWidgets.QLabel(self.centralwidget)
        self.label_lenght.setGeometry(QtCore.QRect(130, 140, 151, 21))
        self.label_lenght.setObjectName("label_lenght")
        self.label_width = QtWidgets.QLabel(self.centralwidget)
        self.label_width.setGeometry(QtCore.QRect(130, 170, 91, 31))
        self.label_width.setObjectName("label_width")
        self.lineEdit_base = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_base.setGeometry(QtCore.QRect(510, 90, 51, 20))
        self.lineEdit_base.setObjectName("lineEdit_base")
        self.lineEdit_radius = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_radius.setGeometry(QtCore.QRect(190, 100, 51, 20))
        self.lineEdit_radius.setObjectName("lineEdit_radius")
        self.lineEdit_lenght = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lenght.setGeometry(QtCore.QRect(190, 180, 51, 20))
        self.lineEdit_lenght.setObjectName("lineEdit_lenght")
        self.lineEdit_width = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_width.setGeometry(QtCore.QRect(190, 140, 51, 20))
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.label_side_lenght = QtWidgets.QLabel(self.centralwidget)
        self.label_side_lenght.setGeometry(QtCore.QRect(430, 180, 121, 21))
        self.label_side_lenght.setObjectName("label_side_lenght")
        self.lineEdit_side_lenght = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_side_lenght.setGeometry(QtCore.QRect(510, 180, 51, 20))
        self.lineEdit_side_lenght.setObjectName("lineEdit_side_lenght")
        self.label_base = QtWidgets.QLabel(self.centralwidget)
        self.label_base.setGeometry(QtCore.QRect(430, 90, 51, 31))
        self.label_base.setObjectName("label_base")
        self.label_height = QtWidgets.QLabel(self.centralwidget)
        self.label_height.setGeometry(QtCore.QRect(430, 130, 61, 31))
        self.label_height.setObjectName("label_height")
        self.lineEdit_height = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_height.setGeometry(QtCore.QRect(510, 140, 51, 20))
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.radioButton_circle = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_circle.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.radioButton_circle.setObjectName("radioButton_circle")
        self.radioButton_rectangle = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_rectangle.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.radioButton_rectangle.setObjectName("radioButton_rectangle")
        self.radioButton_square = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_square.setGeometry(QtCore.QRect(300, 180, 101, 21))
        self.radioButton_square.setObjectName("radioButton_square")
        self.radioButton_triangle = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_triangle.setGeometry(QtCore.QRect(290, 90, 101, 31))
        self.radioButton_triangle.setObjectName("radioButton_triangle")
        self.label_radius = QtWidgets.QLabel(self.centralwidget)
        self.label_radius.setGeometry(QtCore.QRect(140, 220, 151, 21))
        self.label_radius.setText("")
        self.label_radius.setObjectName("label_radius")
        self.label_area_output = QtWidgets.QLabel(self.centralwidget)
        self.label_area_output.setGeometry(QtCore.QRect(230, 270, 221, 61))
        self.label_area_output.setObjectName("label_area_output")
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(290, 230, 91, 41))
        self.button_submit.setObjectName("button_submit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 699, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project 1"))
        self.label.setText(_translate("MainWindow", "Please select a shape"))
        self.label_radius_2.setText(_translate("MainWindow", " Radius"))
        self.label_lenght.setText(_translate("MainWindow", " Lenght"))
        self.label_width.setText(_translate("MainWindow", " Width"))
        self.label_side_lenght.setText(_translate("MainWindow", " Side lenght"))
        self.label_base.setText(_translate("MainWindow", "  Base"))
        self.label_height.setText(_translate("MainWindow", "  Height"))
        self.radioButton_circle.setText(_translate("MainWindow", "   Circle"))
        self.radioButton_rectangle.setText(_translate("MainWindow", "  Rectangle"))
        self.radioButton_square.setText(_translate("MainWindow", "  Square"))
        self.radioButton_triangle.setText(_translate("MainWindow", "   Triangle"))
        self.label_area_output.setText(_translate("MainWindow", "        Area will be oupted here!"))
        self.button_submit.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
